"""Create Materials table

Revision ID: b6196abe842c
Revises: 
Create Date: 2025-04-06 17:51:58.273511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b6196abe842c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materialdb',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('defined_in', sa.Enum('AICONSOLE_CORE', 'PROJECT_DIR', name='assetlocation'), nullable=False),
    sa.Column('default_status', sa.Enum('DISABLED', 'ENABLED', 'FORCED', name='assetstatus'), nullable=False),
    sa.Column('status', sa.Enum('DISABLED', 'ENABLED', 'FORCED', name='assetstatus'), nullable=False),
    sa.Column('content_type', sa.Enum('STATIC_TEXT', 'DYNAMIC_TEXT', 'API', name='materialcontenttype'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('override', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('AGENT', 'MATERIAL', name='assettype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usageexample',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('material_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('example', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materialdb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_table('usageexample')
    op.drop_table('materialdb')
    # ### end Alembic commands ###
