name = "Dalle 3 Image Generator"
version = "0.0.20"
usage = "Use when you need to generate images. Do NOT import and Do NOT create generate_image function, only call it. Do not generate code for displaying the image. The image is displayed using 'how to display image' material."
usage_examples = []
default_status = "enabled"
content_type = "api"
content = "file://./dalle_3_image_generator.py"
