name = "PDF Reader skill"
version = "0.0.2"
usage = "Use this when user asks to read PDF. "
usage_examples = []
default_status = "enabled"
content_type = "static_text"
content_static_text = """
import PyPDF2

# Define the path to the PDF file
pdf_path = '/Users/b/Downloads/Kopia_Zuzanna_Makowska__CV_1.pdf'

# Open the PDF file
with open(pdf_path, 'rb') as file:
    pdf_reader = PyPDF2.PdfReader(file)
    
    # Read the text from each page
    pdf_text = ''
    for page_num in range(len(pdf_reader.pages)):
        page = pdf_reader.pages[page_num]
        pdf_text += page.extract_text()

# Output the text
pdf_text
# START
# END
"""
