name: Run backend checks
on:
  pull_request:

permissions:
  contents: read

jobs:
  run_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry black isort
        cd backend && poetry install
    - name: Run tests
      run: |
        cd backend && poetry run pytest . 
    - name: Run black check
      run: |
        cd backend && black --check .
    - name: Run isort check
      run: |
        cd backend && isort --check-only --atomic .
